package dotai.assets.exporters

import dotai.assets.config.BrandConfig
import java.awt.Color
import java.io.File

class CssExporter(private val outputDir: File) {

    fun export(config: BrandConfig): File {
        val dir = File(outputDir, "css")
        dir.mkdirs()
        val file = File(dir, "brand.css")

        val css = buildString {
            appendLine("/* dotAi Brand Tokens — Generated by dotai-assets */")
            appendLine(":root {")
            appendLine("  /* Primary */")
            appendLine("  --dotai-primary: ${hex(config.colors.primary)};")
            appendLine("  --dotai-primary-dark: ${hex(config.colors.primaryDark)};")
            appendLine("  --dotai-primary-light: ${hex(config.colors.primaryLight)};")
            appendLine()
            appendLine("  /* Dark Theme Backgrounds */")
            appendLine("  --dotai-bg-dark: ${hex(config.colors.backgroundDark)};")
            appendLine("  --dotai-bg-surface: ${hex(config.colors.backgroundSurface)};")
            appendLine("  --dotai-bg-panel: ${hex(config.colors.backgroundPanel)};")
            appendLine("  --dotai-bg-elevated: ${hex(config.colors.backgroundElevated)};")
            appendLine()
            appendLine("  /* Dark Theme Foregrounds */")
            appendLine("  --dotai-fg-primary: ${hex(config.colors.foregroundPrimary)};")
            appendLine("  --dotai-fg-secondary: ${hex(config.colors.foregroundSecondary)};")
            appendLine("  --dotai-fg-muted: ${hex(config.colors.foregroundMuted)};")
            appendLine("  --dotai-fg-border: ${hex(config.colors.foregroundBorder)};")
            appendLine()
            appendLine("  /* Light Theme */")
            appendLine("  --dotai-light-bg: ${hex(config.colors.lightBackground)};")
            appendLine("  --dotai-light-fg: ${hex(config.colors.lightForeground)};")
            appendLine("  --dotai-light-muted: ${hex(config.colors.lightMuted)};")
            appendLine("  --dotai-light-surface: ${hex(config.colors.lightSurface)};")
            appendLine()
            appendLine("  /* Accents */")
            appendLine("  --dotai-accent-emerald: ${hex(config.colors.accentEmerald)};")
            appendLine("  --dotai-accent-amber: ${hex(config.colors.accentAmber)};")
            appendLine("  --dotai-accent-red: ${hex(config.colors.accentRed)};")
            appendLine("  --dotai-accent-yellow: ${hex(config.colors.accentYellow)};")
            appendLine("  --dotai-accent-green: ${hex(config.colors.accentGreen)};")
            appendLine()
            appendLine("  /* Typography */")
            appendLine("  --dotai-font-display: '${config.typography.display}', system-ui, sans-serif;")
            appendLine("  --dotai-font-body: '${config.typography.body}', system-ui, sans-serif;")
            appendLine("  --dotai-font-mono: '${config.typography.mono}', ui-monospace, monospace;")
            appendLine("  --dotai-tracking: ${config.typography.tracking}em;")
            appendLine("}")
            appendLine()
            appendLine("/* Utility classes */")
            appendLine(".dotai-moon-glow {")
            appendLine("  filter: drop-shadow(0 0 20px ${hex(config.colors.primary)}66);")
            appendLine("}")
            appendLine()
            appendLine(".dotai-text-primary { color: var(--dotai-fg-primary); }")
            appendLine(".dotai-text-muted { color: var(--dotai-fg-muted); }")
            appendLine(".dotai-text-accent { color: var(--dotai-primary); }")
            appendLine(".dotai-bg-dark { background-color: var(--dotai-bg-dark); }")
            appendLine(".dotai-bg-surface { background-color: var(--dotai-bg-surface); }")
            appendLine(".dotai-bg-panel { background-color: var(--dotai-bg-panel); }")
        }

        file.writeText(css)
        return file
    }

    private fun hex(c: Color): String =
        "#%02X%02X%02X".format(c.red, c.green, c.blue)
}
